CREATE TABLE IF NOT EXISTS "dim_products" (
	"item_name" VARCHAR(255) NOT NULL,
	"category" VARCHAR(100) NOT NULL,
	"price_per_unit" DECIMAL(10,2) NOT NULL,
	PRIMARY KEY("item_name")
);




CREATE TABLE IF NOT EXISTS "dim_date" (
	"date_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"full_date" DATE NOT NULL UNIQUE,
	"year" INTEGER NOT NULL,
	"month" INTEGER NOT NULL,
	"day" INTEGER NOT NULL,
	"weekday" VARCHAR(10) NOT NULL,
	PRIMARY KEY("date_id")
);




CREATE TABLE IF NOT EXISTS "fact_transactions" (
	"transaction_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"date_id" INTEGER NOT NULL,
	"customer_id" VARCHAR(50) NOT NULL,
	"item_name" VARCHAR(255) NOT NULL,
	"quantity" INTEGER NOT NULL,
	"total_spent" DECIMAL(12,2) NOT NULL,
	"discount_applied" BOOLEAN,
	"payment_method" VARCHAR(50),
	"location" VARCHAR(50),
	PRIMARY KEY("transaction_id")
);



ALTER TABLE "fact_transactions"
ADD FOREIGN KEY("date_id") REFERENCES "dim_date"("date_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_transactions"
ADD FOREIGN KEY("item_name") REFERENCES "dim_products"("item_name")
ON UPDATE NO ACTION ON DELETE NO ACTION;